/* COMMON */
export const CONNECTION_CHANGE = 'CONNECTION_CHANGE';
export const KEYBOARD_SHOW = 'KEYBOARD_SHOW';
export const KEYBOARD_HIDE = 'KEYBOARD_HIDE';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

/* AUTHENTICATE */
export const CHECKING_AUTH_STATUS = 'CHECKING_AUTH_STATUS';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

/* BOOK */
export const FETCH_BOOK = 'FETCH_BOOK';
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const SEARCH_BOOK = 'SEARCH_BOOK';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const FETCH_BOOK_ID = 'FETCH_BOOK_ID';
export const CHANGE_BOOK_INFO = 'CHANGE_BOOK_INFO';
export const RESET_UPDATE_STATE = 'RESET_UPDATE_STATE';

/* ADD BOOK */
export const GOOGLE_SEARCH = 'GOOGLE_SEARCH';
export const GOOGLE_SEARCH_DISMISS = 'GOOGLE_SEARCH_DISMISS';
export const SET_BOOK_INFO = 'SET_BOOK_INFO';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const UPLOAD = 'UPLOAD';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE';

/* NOTE BOOK */
export const FETCH_NOTE = 'FETCH_NOTE';
export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const FETCH_NOTE_FAILURE = 'FETCH_NOTE_FAILURE';
export const TOGGLE_FORM_NOTE = 'TOGGLE_FORM_NOTE';